object Dependency {
    const val targetJvmVersion = "21"
    const val kotlinVersion = "1.9.21"
    const val springBootVersion = "3.2.1"
    const val dependencyManagementVersion = "1.1.0"
    const val detektVersion = "1.23.4"
    const val springCloudVersion = "2023.0.0"
    const val restdocsapiSpecVersion = "0.19.2"
    const val sentryVersion = "6.19.0"
    const val kotestVersion = "5.6.1"
    const val kotestSprintExtensions = "1.1.3"
    const val mockkVersion = "1.13.5"
    const val springMockkVersion = "4.0.2"
    const val openApiStarterWebMvcVersion = "2.0.2"
    const val logbackEncoderVersion = "7.2"
    const val mockitoKotlinVersion = "4.1.0"
    const val prometheusVersion = "1.12.2"
    const val jacocoToolVersion = "0.8.10"
}